a = "Jaydev"
print(a)
b = "I'm In Internshala"
print(b)
print("Concatenation")
print(a+b)
print("Repetation")
print(a+(b*2))
print("Slice")
print(b[7])
print("Range Slice")
print(b[2:8])
print(b[:6])
print(b[7:])
print("In Membership")
print('v' in a)
print('Inter' in b)
print('v' in b)
print("Not In Membership")
print('v' not in b)
print('inter' not in a)
print('J' in a)
